# Generated by Django 4.2.20 on 2025-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famous_Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('descreption1', models.CharField(max_length=100)),
                ('descreption2', models.CharField(max_length=100)),
                ('descreption3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('descreption', models.CharField(max_length=100)),
                ('roooms', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('star', models.CharField(max_length=255)),
            ],
        ),
    ]
